	drop database if exists pizzaria;			
-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 16:39:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `mydb`.`ultpedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`ultpedido` (
  `pedido` INT(15) NOT NULL,
  PRIMARY KEY (`pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ultpedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`ultpedido` (
  `pedido` INT(15) NOT NULL,
  PRIMARY KEY (`pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizzas` (
codigo int(11) not null,
nome varchar(30),
descricao varchar(100),
valor decimal(5,2),
primary key (codigo)
);


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
create table pedidos (
numero INT(11) NOT NULL, 
seq INT(11) NOT NULL,
codigo INT(11),
CONSTRAINT primary key(numero, seq),
CONSTRAINT fk1_pedidos FOREIGN KEY (codigo) references pizzas (codigo)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

create table usuario (
id int primary key auto_increment,
login varchar(10) NOT NULL,
senha varchar(10) NOT NULL
);

insert into usuario (login, senha) values ("admin","admin");



